name: spellcheck

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    name: check spelling
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: spellcheck
        uses: rojopolis/spellcheck-github-actions@0.33.1
        with:
          config_path: 'config/.spellcheck.yml'
